### ISSUE TITLE
convert addresses for different coinTypes (slip44)

### ISSUE THREAD

**Issue by pyramation** [jasbanza/convert-bech32-address#1]
@jasbanza amazing library, thanks for sharing this :) 

If you test this library with any addresses that don't share coinTypes, you'll find that the addresses that are generated are incorrect.

example slip44 coinTypes: 

```
 terra: 330
 osmo: 118
 cosmos: 118
 secret: 529
 akash: 118
```

Let's say you have a `terra` address and want to change to `cosmos`. `terra` uses slip44=330, and `cosmos` uses slip44=118 for example. It seems that the [pubkey to bech32 generation requires hashes](https://bitcointalk.org/index.php?topic=4992632.0), which leads me to believe that it is not possible to do, as it would require deriving the pubkey from bech32 address.

Thanks again for your contributions! Let me know if you may shed some light on this ;)

**Comment by pyramation** [comment]
looks like we have an answer... https://crypto.stackexchange.com/questions/98896/convert-from-one-bech32-address-to-another-with-different-slip44-cointypes

**Comment by jasbanza** [comment]
Hi @pyramation, 

Thanks for the feedback!

Yes, this was something I'm aware of. Unfortunately I'm not aware if it's possible to derive the slip44 cointype from the address. I'm guessing it's not possible, and therefore probably not about to "edit" the slip44 cointype, as the public key would be different I assume.

**Comment by jasbanza** [comment]
Thanks for sharing :)

**Comment by pyramation** [comment]
sure thing! Thanks again!
