### ISSUE TITLE
Incorect with convert to/from evmos

### ISSUE THREAD

**Issue by trulacgc-tcnetwork** [jasbanza/convert-bech32-address#2]
Hi, when i try to convert from cosmos/osmo to evmos, the result is incorrect.
Please look at this.

**Comment by jasbanza** [comment]
This converts with the same cointype ID in the derivation path.

See here:  [https://github.com/satoshilabs/slips/blob/master/slip-0044.md](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

Most cosmos chains are derived with the Slip44 cointype /118'/... in the derivation path... Evmos and a few others use their own cointype id. 

It's not possible to convert addresses between different slip44 cointypes in the HD derivation path, without the original private key / mnemonic


If you imported your wallet with a ledger, it forces all chains addresses to use the same derivation, for compatibility, and therefore evmos would be derived with 118, and this conversion would work fine
